# site settings
title: Ravi
subtitle: Nams
email: ravi.nams@outlook.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: http://ravinams.github.io/
author: Ravi Nams
street_address: Hyderabad
city: Hyderabad
state: Telangana
zip_code: 500081
country: India
phone: (+91) 9848954968

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ravinams
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/ravinams/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
